version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '6606:3306'
  app:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec hanami server --host=0.0.0.0 --port=2300"
    volumes:
      - '.:/myapp'
      - 'bundle:/usr/local/bundle'
    ports:
      - '6300:2300'
    tty: true
    stdin_open: true
    links:
      - db
volumes:
  db-data:
  bundle:
